### ISSUE TITLE
How to fine-tune on my custom dataset

### ISSUE THREAD

**Issue by jmren168** [Sreyan88/LAPE#2]
Thanks for the awesome work.

I'm trying to fine-tune the MAST model on my custom dataset. Is it possible to do? Thanks.

**Comment by Sreyan88** [comment]
Hi @jmren168 ,

Yes ofcourse! What commands have you tried and were unsuccessful? You can follow the upstream/downstream fine-tuning details in the readme and change encoder to MAST for fine-tuning!

**Comment by Sreyan88** [comment]
I have added some details to the Readme for training MAST! Please let me know if it does not work!
